# NumPy array creation

## NumPy arrays via numpy.array

In [2]:
import numpy as np

In [1]:
ar1 = np.array(range(0, 4)) # 1 dimensional array
ar2 = np.array([[0, 3, 5], [2, 7, 8]]) # 1 dimensional array

ar2.shape
ar2.ndim

2

## NumPy array via numpy.arrange

In [5]:
ar3 = np.arange(12)
ar4 = np.arange(3, 10, 3)
ar4

array([3, 6, 9])

## NumPy array via numpy.linspace

In [6]:
ar5 = np.linspace(0, 2.0/3, 4)
ar5

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667])

## NumPy array via various other functions

### numpy.ones

In [4]:
ar7 = np.ones((2, 3, 4))
ar7

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

### numpy.zeros

In [3]:
ar8 = np.zeros((4, 2))
ar8

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

### numpy.eye

In [5]:
ar9 = np.eye(3)
ar9

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### numpy.diag

In [6]:
ar10 = np.diag((2, 1, 4, 6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [9]:
np.random.seed(100)
ar11 = np.random.rand(3)
ar11

array([ 0.54340494,  0.27836939,  0.42451759])

### numpy.empty

In [11]:
ar13 = np.empty((3, 2))
ar13

array([[  1.09682573e-321,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000]])

### numpy.tile

The `np.tile` function allows one to construct an array from a smaller array by repeating it several times on the basis of a parameter.

In [14]:
ar14=np.tile(np.array([[1,2],[6,7]]), 3)
ar14

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [16]:
ar15=np.tile(np.array([[1,2],[6,7]]), (2,2))
ar15

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

# NumPy datatypes

In [6]:
far = np.array([2, -1, 6, 3], dtype='float')
iar = np.array([2, 4, 6, 8])
far = np.array([2., 4, 6, 8])
sar = np.array(['Goodbye','Welcome','Tata','Goodnight'])
bar = np.array([True, False, True]);
iar = far.astype(int)

# NumPy indexing and slicing

In [11]:
ar = np.arange(5)
ar[0], ar[1], ar[-1]
ar[::-1]  #reverse array

ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[2]  # get row 2
ar[:,1] # get column 1

array([ 3,  8, 12])

## Array slicing

In [14]:
ar = 2 * np.arange(6)
ar[1:5:2]

array([2, 6])

## Array masking

In [23]:
np.random.seed(10)
ar = np.random.randint(0, 25, 10)
evenMask = (ar % 2 == 0)
evenNums = ar[evenMask]

ar = np.array(['Hungary','Nigeria', 'Guatemala','','Poland', '','Japan']);
ar[ar==''] = 'USA'

ar = 11 * np.arange(0, 10)
ar[[1,3]]=50
# ar[1, 3] is incorrect, exception will be thrown

# Copies and views

In [25]:
ar1 = np.arange(12)
ar2 = ar1[::2]

np.may_share_memory(ar1, ar2)

ar3 = ar1[::2].copy()
np.may_share_memory(ar1, ar3)

False

# Operations

## Basic operations

In [33]:
ar1 = np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])

ar1.dot(ar2)

l1 = np.array([True, False, True, False])
l2 = np.array([False, False, True, False])

np.logical_and(l1, l2)

ar=np.array([np.pi, np.pi/2])
np.sin(ar)

array([  1.22464680e-16,   1.00000000e+00])